[tool.poetry]
name = "auth0-ai"
version = "0.1.0"
description = "This package provides base abstractions for authentication and authorization in AI applications."
license = "apache-2.0"
homepage = "https://auth0.com"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
auth0-python = "^4.8.1"
openfga-sdk = "^0.9.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.25.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
